version: '3.8'

services:
  web:
    build:
      context: .
      args:
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
        EMAIL: ${EMAIL}
        EMAIL_PASS: ${EMAIL_PASS}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: db
        DB_PORT: ${DB_PORT}
    env_file:
      - .env
    command: gunicorn TMS.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    expose:
      - "8000"
    depends_on:
      - redis
      - rabbitmq
    environment:
      DJANGO_SETTINGS_MODULE: TMS.production-settings
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      EMAIL: ${EMAIL}
      EMAIL_PASS: ${EMAIL_PASS}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: ${DB_PORT}

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  celery:
    build:
      context: .
      args:
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: db
        DB_PORT: ${DB_PORT}
    env_file:
      - .env
    command: celery -A celery worker --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - rabbitmq
    environment:
      DJANGO_SETTINGS_MODULE: TMS.production-settings
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq//

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  postgres_data:
