version: '3.8'

services:
  web:
    build:
      context: .
      args:
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
    env_file:
      - .env
    command: gunicorn project.TMS.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    expose:
      - "8000"  # Exponer el puerto para Nginx
    depends_on:
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: project.TMS.production-settings
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

  redis:
    image: redis:alpine
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  celery:
    build:
      context: .
      args:
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
    env_file:
      - .env
    command: celery -A project.TMS worker --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: project.TMS.production-settings
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Exponer el puerto 80 para acceso externo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Configuración personalizada de Nginx
    depends_on:
      - web
