version: '3.8'

services:
  web:
    build:
      context: .
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
    command: gunicorn project.TMS.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: project.TMS.production-settings

  redis:
    image: redis:alpine
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  celery:
    build:
      context: .
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
    command: celery -A project.TMS worker --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: project.TMS.production-settings

env_file:
  - .env
