# Generated by Django 3.2.25 on 2024-10-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='email',
            field=models.EmailField(help_text='Correo utilizado para enviar notificaciones', max_length=254),
        ),
    ]
